version: '1.0'
services:
  app:  #불러온 이미지 기반으로 컨테이너에 올리기 위해 새로 빌드 하게 될 이미지 이름
    build:   # 불러올 이미지 & 기반으로 빌드
      context: ./
      dockerfile: ./Dockerfile
    container_name: arjs   # 올릴 컨테이너 이름
    ports:                     # 로컬과 연결할 포트 번호
      - "443:443"              # nginx 암호화 프로토콜
      - "8080:80"              # 8080은 로컬에, 80은 컨테이너에 연결되는 포트번호를 말한다.
    environment:
      NODE_ENV: production     # .env 환경에서 설정해준 내용들
      BASE_URL: '/'
      VUE_APP_SERVER: http://192.168.0.106:3001